import React from 'react';
import { NavLink } from 'react-router-dom';
import { Sparkles, ArrowLeft } from 'lucide-react';
import bgNebula from '../../assets/bg-nebula.png';
import Footer from '../../components/Footer';

const Pricing = () => {
    return (
        <div className="min-h-screen relative bg-black text-white font-sans flex flex-col">
            {/* Background */}
            <div className="fixed inset-0 z-0 opacity-40">
                <img src={bgNebula} alt="Nebula" className="w-full h-full object-cover" />
                <div className="absolute inset-0 bg-black/60"></div>
            </div>

            <div className="relative z-10 flex-1 max-w-4tl mx-auto px-6 py-12">
                <NavLink to="/" className="inline-flex items-center gap-2 text-white/50 hover:text-white mb-8 transition-colors">
                    <ArrowLeft size={16} /> Back to Auralume
                </NavLink>

                <h1 className="text-4xl md:text-5xl font-serif text-gold mb-6">Service Pricing</h1>

                <div className="glass-panel p-8 rounded-2xl border border-white/10 backdrop-blur-xl">
                    <div className="flex flex-col md:flex-row gap-8 items-start">

                        {/* Product Card */}
                        <div className="w-full md:w-1/2 bg-white/5 rounded-xl p-6 border border-gold/20">
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h3 className="text-xl font-bold text-white">Cosmic Soulmate Report</h3>
                                    <p className="text-sm text-white/60">Unlock your astrological compatibility</p>
                                </div>
                                <Sparkles className="text-gold" />
                            </div>

                            <div className="text-4xl font-serif text-gold mb-6">$9.99 <span className="text-sm font-sans text-white/40">one-time</span></div>

                            <ul className="space-y-3 text-sm text-white/80 mb-6">
                                <li className="flex gap-2">✓ Full Astrological Birth Chart Analysis</li>
                                <li className="flex gap-2">✓ Soulmate Aura Art Generation</li>
                                <li className="flex gap-2">✓ Gemstone Energy Recommendation</li>
                                <li className="flex gap-2">✓ Future Transit Alerts</li>
                            </ul>

                            <a href="/soulmate" className="block text-center btn-cosmic w-full py-3 rounded-lg">
                                Buy Now
                            </a>
                        </div>

                        {/* Description */}
                        <div className="w-full md:w-1/2 text-white/70 leading-relaxed">
                            <h3 className="text-lg font-bold text-white mb-3">What you get</h3>
                            <p className="mb-4">
                                Auralume provides personalized digital astrology reports generated by advanced AI.
                                By purchasing the Soulmate Report, you gain immediate digital access to:
                            </p>
                            <ul className="list-disc list-inside space-y-2 pl-2 mb-6 text-sm">
                                <li>A high-resolution, downloadable Aura Portrait.</li>
                                <li>Detailed compatibility insights based on your birth data.</li>
                                <li>Customized spiritual advice and gemstone matching.</li>
                            </ul>

                            <h3 className="text-lg font-bold text-white mb-3">Currency</h3>
                            <p className="text-sm">All prices are processed in USD. No subscription required.</p>
                        </div>
                    </div>
                </div>

                <Footer />
            </div>
        </div>
    );
};

export default Pricing;
